# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: dynamical_system 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "dynamical_system"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Luke Grecki"]
  s.date = "2016-01-15"
  s.description = "Define simple dynamical systems, evolve them, and calculate properties."
  s.email = "lukegrecki@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/dynamical_system.rb",
    "test/helper.rb",
    "test/test_dynamical_system.rb"
  ]
  s.homepage = "http://github.com/lukegrecki/dynamical_system"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "A simple ruby library for discrete dynamical systems"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

